[project]
name = "hf-models"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "langchain-google-genai>=4.2.1",
    "langchain-ollama>=1.0.1",
    "lightgbm>=4.6.0",
    "matplotlib>=3.10.9",
    "openpyxl>=3.1.5",
    "pandas>=3.0.0",
    "scikit-learn>=1.8.0",
    "streamlit>=1.56.0",
    "torch>=2.10.0",
    "torchvision>=0.25.0",
    "websockets>=16.0",
    "xgboost>=3.2.0",
]
